name: Skywars
author: Mirvin1
main: Mirvin1\Main
version: 0.0.1
api: 4.0.0
load: POSTWORLD
commands:
  sw:
    description: "Управление игрой."
    usage: "/sw help"
    permission: sw.command.mirvin1
permissions:
  sw.command.mirvin01:
    default: op
    description: "Выдаёт право на использование всех команд плагина." 
